### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by jared-jensen** [mxtra/yeelight-ha#3]
Hey!

Nice work on the component. I had just started working on it and thought I'd check github to see if anyone got ahead of me.

I spent most of the night tonight working on getting automatic discovery working. Testing with the netdisco module, it looks like I got everything is correct. I think I can get the two to work together pretty easily since both pieces are in usable states -- I'll use the Hue bulb for an example on how to accomplish this.

https://github.com/jared-jensen/netdisco/tree/yeelight-bulbs

I'm going to fork your project and work on adding my autodiscovery stuff.

**Comment by mxtra** [comment]
Great! Since you already opened a PR I will close this issue.
